name: GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      actions: write
      checks: write
      contents: write
      pages: write
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build docs
        run: pnpm exec rimraf docs && pnpm exec typedoc src/index.ts --out docs

      - name: Build
        run: pnpm build

      - name: Copy demo files
        run: |
          mkdir -p docs/demo/world
          cp demo/index.html docs/demo/index.html
          cp dist/index.js docs/demo/index.js
          cp dist/koe-worklet.js docs/demo/koe-worklet.js
          cp dist/world/worldline.js docs/demo/world/worldline.js
          cp dist/world/worldline.wasm docs/demo/world/worldline.wasm
          mkdir -p docs/demo/utautts
          cp dist/utautts/wasm_exec.js docs/demo/utautts/wasm_exec.js
          cp dist/utautts/utautts.wasm docs/demo/utautts/utautts.wasm

      - name: Add .nojekyll
        run: touch ./docs/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: ./docs

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
